[build]
  command = "curl -fsSL https://raw.githubusercontent.com/flutter/flutter/master/bin/flutter | bash && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter build web --release"
  publish = "build/web"